# Generated by Django 4.2 on 2025-10-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='analysis_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='matched_keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='cv',
            name='extracted_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cv',
            name='parsed_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='requirements',
            field=models.JSONField(default=list),
        ),
    ]
