# Generated by Django 4.2 on 2025-11-02 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvs', '0002_alter_analysisresult_analysis_details_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisresult',
            options={'ordering': ['-created_at'], 'verbose_name': "Résultat d'analyse", 'verbose_name_plural': "Résultats d'analyse"},
        ),
        migrations.AlterModelOptions(
            name='cv',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'CV', 'verbose_name_plural': 'CVs'},
        ),
        migrations.AlterModelOptions(
            name='joboffer',
            options={'ordering': ['-created_at'], 'verbose_name': "Offre d'emploi", 'verbose_name_plural': "Offres d'emploi"},
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='missing_keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='deadline',
            field=models.DateField(default='2025-12-31'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joboffer',
            name='experience_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='job_type',
            field=models.CharField(default='Temps plein', max_length=100),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='location',
            field=models.CharField(default='Non spécifié', max_length=255),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='salary_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publiée'), ('closed', 'Fermée')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='cvs.cv'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='job_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='cvs.joboffer'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='recruteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='analysisresult',
            unique_together={('cv', 'job_offer')},
        ),
    ]
