# Generated by Django 4.2.16 on 2025-11-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0003_alter_analysisresult_options_alter_cv_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='analysisresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='job_offer_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='analysis_details',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='job_offer',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='status',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='JobOffer',
        ),
    ]
