# Generated by Django 4.2.16 on 2025-11-20 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvs', '0004_alter_analysisresult_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
