# Generated by Django 4.2.16 on 2025-11-20 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvs', '0005_analysisresult_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='created_by',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='analyzed_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a effectué cette analyse', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_performed', to=settings.AUTH_USER_MODEL),
        ),
    ]
